name: Bug Report
description: Report an encountered bug.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! If you have usage questions, please use the [Community Discussions](https://github.com/axivo/website/discussions).
  - type: checkboxes
    attributes:
      label: Existing Issues
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened
      description: What did you expect to happen?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else
      description: |
        Links? References? Anything that will provide more context about the issue you are encountering.
        > You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/axivo/website/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project's Code of Conduct
          required: true
