name: Feature Request
description: Suggest an idea for this project.
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request! If you have usage questions, please use the [Community Discussions](https://github.com/axivo/website/discussions).
  - type: checkboxes
    attributes:
      label: Existing Issues
      description: Please search to see if an issue already exists for the feature request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: related-problem
    attributes:
      label: Related Problem
      description: Is your feature request related to a problem?
      value: "Please describe the related problem."
    validations:
      required: true
  - type: textarea
    id: solution-implementation
    attributes:
      label: Solution Implementation
      description: Describe the solution you would like to see implemented.
    validations:
      required: true
  - type: textarea
    id: solution-alternatives
    attributes:
      label: Solution Alternatives
      description: Describe any solution alternatives you've considered.
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else
      description: |
        Links? References? Anything that will provide more context about the feature request.
        > [!TIP]
        > You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/axivo/k3s-cluster/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow project's Code of Conduct
          required: true
