name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - global/**
      - k3s-cluster/**
  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: pages

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: 0.123.0

      - name: Build Content
        env:
          HUGO_ENV: production
          TZ: America/New_York
        run: |
          hugo --gc --minify -s ./docs
          hugo --gc --minify -s ./k3s-cluster

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    name: Deploy Documentation to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Documentation
        id: deployment
        uses: actions/deploy-pages@v4
