name: Modules

on:
  pull_request:
    paths:
      - '**/go.mod'
      - '**/go.sum'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

permissions:
  contents: write
  issues: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.145.0
          extended: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node dependencies
        run: npm install handlebars

      - name: Configure repository
        uses: actions/github-script@v7
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.configureRepository();

      - name: Update module checksums
        uses: actions/github-script@v7
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.updateModules();

      - name: Report workflow issue
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.reportIssue();
